export const DEFAULT_DISPLAY_DATE_FORMAT = "DD.MM.YYYY, HH:mm:ss"
export const DEFAULT_SHORT_DATE_FORMAT = "DD.MM.YYYY"

export const GITLAB_DATE_FORMAT_START = "YYYY-MM-DD 00:00:00"
export const GITLAB_DATE_FORMAT_END = "YYYY-MM-DD 23:59:59"

export const GITHUB_DATE_FORMAT_START = "YYYY-MM-DDT00:00:00Z"
export const GITHUB_DATE_FORMAT_END = "YYYY-MM-DDT23:59:59Z"